[project]
name = "ptsa"
version = "0.1.0"
description = "PTSA Library"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Malvern Yap" }
]
dependencies = [
    "geographiclib",
    "geopandas",
    "shapely"
]

[project.optional-dependencies]
dev = [    
    "black",
    "build", 
    "isort",
    "pytest",
    "ruff",
    "setuptools"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 200

[tool.ruff]
line-length = 200